# Generated by Django 4.1.4 on 2022-12-22 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0006_alter_usermessage_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermessage',
            options={'verbose_name': 'Сообщение от пользователя', 'verbose_name_plural': 'Сообщения от пользователей'},
        ),
    ]
